swagger: "2.0"
info:
  title: Learn Catalog MCP Server
  description: Microsoft Learn Catalog using MCP server. Search modules and learning paths.
  version: "1.0"
host: mcp-learn-catalog-app-azevddenc4cmdzdp.westeurope-01.azurewebsites.net
basePath: /
schemes:
  - https
definitions:
  QueryResponse:
    type: object
    properties:
      jsonrpc:
        type: string
      id:
        type: string
      method:
        type: string
      params:
        type: object
      result:
        type: object
        properties:
          content:
            type: array
            items:
              type: object
              properties:
                type:
                  type: string
                text:
                  type: string
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      uid:
                        type: string
                      title:
                        type: string
                      summary:
                        type: string
                      url:
                        type: string
      error:
        type: object
paths:
  /sse:
    get:
      summary: Learn Catalog MCP Server
      parameters:
        - in: query
          name: sessionId
          type: string
          required: false
      produces:
        - application/json
      responses:
        "200":
          description: Immediate Response
          schema:
            $ref: "#/definitions/QueryResponse"
        "201":
          description: Created and will follow callback
      operationId: LearnCatalogMCP
      tags:
        - Agentic
        - McpSse
securityDefinitions: {}
security: []