name: Deploy Node.js app to Azure Web App
'on':
  push:
    branches:
    - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build || echo 'No build script'
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: mcp-learn-catalog-app-azevddenc4cmdzdp
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: .
